version: "2"

services:

  clair_db:
    image: arminc/clair-db:latest
    container_name: clair_db
    networks:
      - default
    mem_limit: 512m

  clair_local_scan:
    image: arminc/clair-local-scan:latest
    container_name: clair_local_scan
    links:
      - clair_db:postgres
    depends_on:
      - clair_db
    networks:
      - default
    mem_limit: 512m

  clair_local_scanner:
    image: zebby76/clair-scanner:latest
    container_name: clair_local_scanner
    command: ["--clair","${BATS_CLAIR_LOCAL_ENDPOINT_URL}","--ip","${BATS_CLAIR_LOCAL_SCANNER_IP}","--all","-l","/opt/clair/config/clair-report.log","-r","/opt/clair/config/clair-report.json","-w","/opt/clair/config/clair-whitelist.yml","${BATS_CLAIR_SCAN_DOCKER_IMAGE_NAME}"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - clair_config:/opt/clair/config
    links:
      - clair_db:postgres
    depends_on:
      - clair_db
    networks:
      - default
    mem_limit: 512m

  mysql:
    image: docker.io/mysql/mysql-server:5.7
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${BATS_DB_PASSWORD}
      - MYSQL_USER=${BATS_DB_USER}
      - MYSQL_PASSWORD=${BATS_DB_PASSWORD}
      - MYSQL_DATABASE=${BATS_DB_NAME}
      - DEBUG=false
    volumes:
      - data_mysql:/var/lib/mysql
    networks:
      - default
    mem_limit: 512m

  nginx:
    image: docker.io/nginx:alpine
    container_name: nginx
    ports:
      - 9000:9000
    command: [nginx, '-g', 'daemon off;']
    depends_on:
      - php-fpm
    volumes:
      - php_sock:/var/run/php-fpm
      - php_src:/usr/share/nginx/html
      - nginx_config:/etc/nginx/conf.d
    networks:
      - default
    mem_limit: 128m

  php-fpm:
    image: ${BATS_PHP_DOCKER_IMAGE_NAME}
    container_name: php-fpm
    environment: 
      - PHP_FPM_MAX_CHILDREN=${BATS_PHP_FPM_MAX_CHILDREN}
      - PHP_FPM_REQUEST_MAX_MEMORY_IN_MEGABYTES=${BATS_PHP_FPM_REQUEST_MAX_MEMORY_IN_MEGABYTES}
      - CONTAINER_HEAP_PERCENT=${BATS_CONTAINER_HEAP_PERCENT}
      - DB_DRIVER=${BATS_DB_DRIVER}
      - DB_HOST=${BATS_DB_HOST}
      - DB_PORT=${BATS_DB_PORT}
      - DB_USER=${BATS_DB_USER}
      - DB_PASSWORD=${BATS_DB_PASSWORD}
      - DB_NAME=${BATS_DB_NAME}
    links:
      - ${BATS_STORAGE_SERVICE_NAME}:${BATS_STORAGE_SERVICE_NAME}
    depends_on:
      - ${BATS_STORAGE_SERVICE_NAME}
    command: ["php-fpm","-F","-R"]
    volumes:
      - php_scripts:/opt/bin/container-entrypoint.d
      - php_sock:/var/run/php-fpm
      - php_src:/usr/share/nginx/html
    networks:
      - default
    build:
      context: .
      args:
        VERSION_ARG: ${PHP_VERSION}
        RELEASE_ARG: ${RELEASE_NUMBER}
        BUILD_DATE_ARG: ${BUILD_DATE}
        VCS_REF_ARG: ${VCS_REF}
        AWS_CLI_VERSION_ARG: ${AWS_CLI_VERSION}
    mem_limit: 512m

volumes:
  clair_config:
    external:
      name: ${BATS_CLAIR_LOCAL_SCANNER_CONFIG_VOLUME_NAME}
  data_mysql:
    external:
      name: ${BATS_MYSQL_VOLUME_NAME}
  php_scripts:
    external:
      name: ${BATS_PHP_SCRIPTS_VOLUME_NAME}
  php_sock:
    external:
      name: ${BATS_PHP_SOCKET_VOLUME_NAME}
  php_src:
    external:
      name: ${BATS_SOURCES_VOLUME_NAME}
  nginx_config:
    external:
      name: ${BATS_NGINX_CONFIG_VOLUME_NAME}

networks:
  default:
    external:
      name: docker_default
