name: Docker Release (Python 2)

run-name: Docker Release ${{ github.ref_name }} by @${{ github.actor }}

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:

  init:

    runs-on: ubuntu-20.04

    outputs:
      version-patch: ${{ steps.prep.outputs.version-patch }}
      version-minor: ${{ steps.prep.outputs.version-minor }}
      version-major: ${{ steps.prep.outputs.version-major }}
      build-date: ${{ steps.prep.outputs.build-date }}
      phpcli-prd-docker-image-name: ${{ steps.prep.outputs.phpcli-prd-docker-image-name }}
      phpcli-dev-docker-image-name: ${{ steps.prep.outputs.phpcli-dev-docker-image-name }}
      github-ci-run-id: ${{ steps.prep.outputs.github-ci-run-id }}
      github-ci-sha-short: ${{ steps.prep.outputs.github-ci-sha-short }}
      github-ci-sha: ${{ steps.prep.outputs.github-ci-sha }}
      aws-cli-version: ${{ steps.prep.outputs.aws-cli-version }}

    steps:
      - uses: actions/checkout@v3

      - name: Fill GitHub Environment Variables
        uses: FranzDiebold/github-env-vars-action@v2

      - name: Fill PHP Version Environment Variable
        uses: c-py/action-dotenv-to-setenv@v4
        with:
          env-file: .build.env

      - name: Prepare Workflow Environment
        id: prep
        run: |
          VERSION_MAJOR_MINOR_PATCH=${GITHUB_REF_NAME}
          VERSION_MAJOR_MINOR=${VERSION_MAJOR_MINOR_PATCH%.*}
          VERSION_MAJOR=${VERSION_MAJOR_MINOR%.*}
          echo "phpcli-prd-docker-image-name=${PHPCLI_PRD_DOCKER_IMAGE_NAME}" >> $GITHUB_OUTPUT
          echo "phpcli-dev-docker-image-name=${PHPCLI_DEV_DOCKER_IMAGE_NAME}" >> $GITHUB_OUTPUT
          echo "version-patch=${VERSION_MAJOR_MINOR_PATCH}" >> $GITHUB_OUTPUT
          echo "version-minor=${VERSION_MAJOR_MINOR}" >> $GITHUB_OUTPUT
          echo "version-major=${VERSION_MAJOR}" >> $GITHUB_OUTPUT
          echo "build-date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "github-ci-sha-short=${CI_SHA_SHORT}" >> $GITHUB_OUTPUT
          echo "github-ci-sha=${CI_SHA}" >> $GITHUB_OUTPUT
          echo "github-ci-run-id=${CI_RUN_ID}" >> $GITHUB_OUTPUT
          echo "aws-cli-version=${AWS_CLI_VERSION}" >> $GITHUB_OUTPUT

  build:

    strategy:
      matrix:
        py2-node-version: [12,13,14,15,16]

    runs-on: ubuntu-20.04
    needs: init
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Fill "${{ needs.init.outputs.phpcli-prd-docker-image-name }} ( py2-node${{ matrix.py2-node-version }} )" Docker Image metadata
        id: meta-phpcli-prd
        uses: docker/metadata-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: "${{ needs.init.outputs.phpcli-prd-docker-image-name }}"
          tags: |
            type=raw,value=${{ needs.init.outputs.github-ci-sha-short }}-py2-node${{ matrix.py2-node-version }}
            type=raw,value=${{ needs.init.outputs.version-patch }}-py2-node${{ matrix.py2-node-version }}
            type=raw,value=${{ needs.init.outputs.version-minor }}-py2-node${{ matrix.py2-node-version }}
            type=raw,value=${{ needs.init.outputs.version-major }}-py2-node${{ matrix.py2-node-version }}
            type=raw,value=latest

      - name: Fill "${{ needs.init.outputs.phpcli-dev-docker-image-name }} ( py2-node${{ matrix.py2-node-version }} )" Docker Image metadata
        id: meta-phpcli-dev
        uses: docker/metadata-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: "${{ needs.init.outputs.phpcli-dev-docker-image-name }}"
          tags: |
            type=raw,value=${{ needs.init.outputs.github-ci-sha-short }}-py2-node${{ matrix.py2-node-version }}
            type=raw,value=${{ needs.init.outputs.version-patch }}-py2-node${{ matrix.py2-node-version }}
            type=raw,value=${{ needs.init.outputs.version-minor }}-py2-node${{ matrix.py2-node-version }}
            type=raw,value=${{ needs.init.outputs.version-major }}-py2-node${{ matrix.py2-node-version }}
            type=raw,value=latest

      - name: Build "${{ needs.init.outputs.phpcli-prd-docker-image-name }} ( py2-node${{ matrix.py2-node-version }} )" Docker Image
        id: build-phpcli-prd
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: Dockerfile.cli-py2-node${{ matrix.py2-node-version }}
          target: cli-prd
          build-args: |
            VERSION_ARG=${{ needs.init.outputs.version-patch }}
            RELEASE_ARG=${{ needs.init.outputs.github-ci-run-id }}
            VCS_REF_ARG=${{ needs.init.outputs.github-ci-sha }}
            BUILD_DATE_ARG=${{ needs.init.outputs.build-date }}
            NODE_VERSION_ARG=${{ matrix.py2-node-version }}
          tags: ${{ steps.meta-phpcli-prd.outputs.tags }}
          labels: ${{ steps.meta-phpcli-prd.outputs.labels }}
          outputs: type=docker,dest=/tmp/phpcli-prd-py2-node${{ matrix.py2-node-version }}-builded.tar

      - name: Build "${{ needs.init.outputs.phpcli-dev-docker-image-name }} ( py2-node${{ matrix.py2-node-version }} )" Docker Image
        id: build-phpcli-dev
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: Dockerfile.cli-py2-node${{ matrix.py2-node-version }}
          target: cli-dev
          build-args: |
            VERSION_ARG=${{ needs.init.outputs.version-patch }}
            RELEASE_ARG=${{ needs.init.outputs.github-ci-run-id }}
            VCS_REF_ARG=${{ needs.init.outputs.github-ci-sha }}
            BUILD_DATE_ARG=${{ needs.init.outputs.build-date }}
            NODE_VERSION_ARG=${{ matrix.py2-node-version }}
          tags: ${{ steps.meta-phpcli-dev.outputs.tags }}
          labels: ${{ steps.meta-phpcli-dev.outputs.labels }}
          outputs: type=docker,dest=/tmp/phpcli-dev-py2-node${{ matrix.py2-node-version }}-builded.tar

      - name: Install Docker Squash
        id: install-squash
        run: |
          pip install docker-squash

      - name: Squash "${{ needs.init.outputs.phpcli-prd-docker-image-name }} ( py2-node${{ matrix.py2-node-version }} )" Docker Image
        id: squash-phpcli-prd
        run: |
          cat /tmp/phpcli-prd-py2-node${{ matrix.py2-node-version }}-builded.tar | docker load
          docker-squash --verbose --message "Build and Squashed in GitHub Action" \
            --tag ${{ needs.init.outputs.phpcli-prd-docker-image-name }}:${{ needs.init.outputs.github-ci-sha-short }}-py2-node${{ matrix.py2-node-version }} \
            --output-path /tmp/phpcli-prd-py2-node${{ matrix.py2-node-version }}-squashed.tar \
            --cleanup \
            ${{ needs.init.outputs.phpcli-prd-docker-image-name }}:${{ needs.init.outputs.github-ci-sha-short }}-py2-node${{ matrix.py2-node-version }}
          cat /tmp/phpcli-prd-py2-node${{ matrix.py2-node-version }}-squashed.tar | docker load         
          tags=$(echo "${{ steps.meta-phpcli-prd.outputs.tags }}" | tr "\n" " ")
          for tag in $tags; do
            docker tag ${{ needs.init.outputs.phpcli-prd-docker-image-name }}:${{ needs.init.outputs.github-ci-sha-short }}-py2-node${{ matrix.py2-node-version }} $tag
          done
          docker save --output /tmp/phpcli-prd-py2-node${{ matrix.py2-node-version }}-final.tar $tags

      - name: Squash "${{ needs.init.outputs.phpcli-dev-docker-image-name }} ( py2-node${{ matrix.py2-node-version }} )" Docker Image
        id: squash-phpcli-dev
        run: |
          cat /tmp/phpcli-dev-py2-node${{ matrix.py2-node-version }}-builded.tar | docker load
          docker-squash --verbose --message "Build and Squashed in GitHub Action" \
            --tag ${{ needs.init.outputs.phpcli-dev-docker-image-name }}:${{ needs.init.outputs.github-ci-sha-short }}-py2-node${{ matrix.py2-node-version }} \
            --output-path /tmp/phpcli-dev-py2-node${{ matrix.py2-node-version }}-squashed.tar \
            --cleanup \
            ${{ needs.init.outputs.phpcli-dev-docker-image-name }}:${{ needs.init.outputs.github-ci-sha-short }}-py2-node${{ matrix.py2-node-version }}
          cat /tmp/phpcli-dev-py2-node${{ matrix.py2-node-version }}-squashed.tar | docker load         
          tags=$(echo "${{ steps.meta-phpcli-dev.outputs.tags }}" | tr "\n" " ")
          for tag in $tags; do
            docker tag ${{ needs.init.outputs.phpcli-dev-docker-image-name }}:${{ needs.init.outputs.github-ci-sha-short }}-py2-node${{ matrix.py2-node-version }} $tag
          done
          docker save --output /tmp/phpcli-dev-py2-node${{ matrix.py2-node-version }}-final.tar $tags

      - name: Check Docker Images
        run: |
          docker image inspect ${{ needs.init.outputs.phpcli-prd-docker-image-name }}:${{ needs.init.outputs.github-ci-sha-short }}-py2-node${{ matrix.py2-node-version }}
          docker image inspect ${{ needs.init.outputs.phpcli-dev-docker-image-name }}:${{ needs.init.outputs.github-ci-sha-short }}-py2-node${{ matrix.py2-node-version }}
          docker history ${{ needs.init.outputs.phpcli-prd-docker-image-name }}:${{ needs.init.outputs.github-ci-sha-short }}-py2-node${{ matrix.py2-node-version }}
          docker history ${{ needs.init.outputs.phpcli-dev-docker-image-name }}:${{ needs.init.outputs.github-ci-sha-short }}-py2-node${{ matrix.py2-node-version }}

      - name: Upload "${{ needs.init.outputs.phpcli-prd-docker-image-name }} ( py2-node${{ matrix.py2-node-version }} )" Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: phpcli-prd
          path: /tmp/phpcli-prd-py2-node${{ matrix.py2-node-version }}-final.tar

      - name: Upload "${{ needs.init.outputs.phpcli-dev-docker-image-name }} ( py2-node${{ matrix.py2-node-version }} )" Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: phpcli-dev
          path: /tmp/phpcli-dev-py2-node${{ matrix.py2-node-version }}-final.tar

  tests:

    strategy:
      matrix:
        py2-node-version: [12,13,14,15,16]

    runs-on: ubuntu-20.04
    needs: [init,build]
    steps:
      - uses: actions/checkout@v3

      - name: Setup BATS testing framework
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download "${{ needs.init.outputs.phpcli-prd-docker-image-name }} ( py2-node${{ matrix.py2-node-version }} )" Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: phpcli-prd
          path: /tmp

      - name: Download "${{ needs.init.outputs.phpcli-dev-docker-image-name }} ( py2-node${{ matrix.py2-node-version }} )" Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: phpcli-dev
          path: /tmp

      - name: Load Docker images
        run: |
          docker load --input /tmp/phpcli-prd-py2-node${{ matrix.py2-node-version }}-final.tar
          docker load --input /tmp/phpcli-dev-py2-node${{ matrix.py2-node-version }}-final.tar
          docker image ls -a

      - name: Scan "${{ needs.init.outputs.phpcli-prd-docker-image-name }}:${{ needs.init.outputs.github-ci-sha-short }}-py2-node${{ matrix.py2-node-version }}" Docker image
        uses: anchore/scan-action@v3
        id: scan-phpcli
        with:
          image: ${{ needs.init.outputs.phpcli-prd-docker-image-name }}:${{ needs.init.outputs.github-ci-sha-short }}
          fail-build: false
          severity-cutoff: critical
          output-format: table

      - name: Scan "${{ needs.init.outputs.phpcli-dev-docker-image-name }}:${{ needs.init.outputs.github-ci-sha-short }}-py2-node${{ matrix.py2-node-version }}" Docker image
        uses: anchore/scan-action@v3
        id: scan-phpcli-dev
        with:
          image: ${{ needs.init.outputs.phpcli-dev-docker-image-name }}:${{ needs.init.outputs.github-ci-sha-short }}
          fail-build: false
          severity-cutoff: critical
          output-format: table

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Test "${{ needs.init.outputs.phpcli-prd-docker-image-name }}:${{ needs.init.outputs.github-ci-sha-short }}-py2-node${{ matrix.py2-node-version }}" Docker Image
        env:
          DOCKER_IMAGE_NAME: ${{ needs.init.outputs.phpcli-prd-docker-image-name }}:${{ needs.init.outputs.github-ci-sha-short }}-py2-node${{ matrix.py2-node-version }}
          PHP_VERSION: ${{ needs.init.outputs.version-patch }}
        run: |
          docker network create docker_default
          docker pull appropriate/curl:latest
          bats -r test/tests.cli.bats

      - name: Test "${{ needs.init.outputs.phpcli-dev-docker-image-name }}:${{ needs.init.outputs.github-ci-sha-short }}-py2-node${{ matrix.py2-node-version }}" Docker Image
        env:
          DOCKER_IMAGE_NAME: ${{ needs.init.outputs.phpcli-dev-docker-image-name }}:${{ needs.init.outputs.github-ci-sha-short }}-py2-node${{ matrix.py2-node-version }}
          PHP_VERSION: ${{ needs.init.outputs.version-patch }}
        run: |
          bats -r test/tests.cli.bats

  push:

    strategy:
      matrix:
        py2-node-version: [12,13,14,15,16]

    runs-on: ubuntu-20.04
    needs:  [init,tests]

    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download "${{ needs.init.outputs.phpcli-prd-docker-image-name }} ( py2-node${{ matrix.py2-node-version }} )" Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: phpcli-prd
          path: /tmp

      - name: Download "${{ needs.init.outputs.phpcli-dev-docker-image-name }} ( py2-node${{ matrix.py2-node-version }} )" Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: phpcli-dev
          path: /tmp

      - name: Load Docker images
        run: |
          docker load --input /tmp/phpcli-prd-py2-node${{ matrix.py2-node-version }}-final.tar
          docker load --input /tmp/phpcli-dev-py2-node${{ matrix.py2-node-version }}-final.tar
          docker image ls -a

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker images
        run: |
          docker push ${{ needs.init.outputs.phpcli-prd-docker-image-name }}:${{ needs.init.outputs.github-ci-sha-short }}-py2-node${{ matrix.py2-node-version }}
          docker push ${{ needs.init.outputs.phpcli-prd-docker-image-name }}:${{ needs.init.outputs.version-patch }}-py2-node${{ matrix.py2-node-version }}
          docker push ${{ needs.init.outputs.phpcli-prd-docker-image-name }}:${{ needs.init.outputs.version-minor }}-py2-node${{ matrix.py2-node-version }}
          docker push ${{ needs.init.outputs.phpcli-prd-docker-image-name }}:${{ needs.init.outputs.version-major }}-py2-node${{ matrix.py2-node-version }}
          docker push ${{ needs.init.outputs.phpcli-prd-docker-image-name }}:latest
          docker push ${{ needs.init.outputs.phpcli-dev-docker-image-name }}:${{ needs.init.outputs.github-ci-sha-short }}-py2-node${{ matrix.py2-node-version }}
          docker push ${{ needs.init.outputs.phpcli-dev-docker-image-name }}:${{ needs.init.outputs.version-patch }}-py2-node${{ matrix.py2-node-version }}
          docker push ${{ needs.init.outputs.phpcli-dev-docker-image-name }}:${{ needs.init.outputs.version-minor }}-py2-node${{ matrix.py2-node-version }}
          docker push ${{ needs.init.outputs.phpcli-dev-docker-image-name }}:${{ needs.init.outputs.version-major }}-py2-node${{ matrix.py2-node-version }}
          docker push ${{ needs.init.outputs.phpcli-dev-docker-image-name }}:latest

      - name: Check Docker Images pull's
        run: |
          docker pull ${{ needs.init.outputs.phpcli-prd-docker-image-name }}:${{ needs.init.outputs.github-ci-sha-short }}-py2-node${{ matrix.py2-node-version }}
          docker pull ${{ needs.init.outputs.phpcli-prd-docker-image-name }}:${{ needs.init.outputs.version-patch }}-py2-node${{ matrix.py2-node-version }}
          docker pull ${{ needs.init.outputs.phpcli-prd-docker-image-name }}:${{ needs.init.outputs.version-minor }}-py2-node${{ matrix.py2-node-version }}
          docker pull ${{ needs.init.outputs.phpcli-prd-docker-image-name }}:${{ needs.init.outputs.version-major }}-py2-node${{ matrix.py2-node-version }}
          docker pull ${{ needs.init.outputs.phpcli-prd-docker-image-name }}:latest
          docker pull ${{ needs.init.outputs.phpcli-dev-docker-image-name }}:${{ needs.init.outputs.github-ci-sha-short }}-py2-node${{ matrix.py2-node-version }}
          docker pull ${{ needs.init.outputs.phpcli-dev-docker-image-name }}:${{ needs.init.outputs.version-patch }}-py2-node${{ matrix.py2-node-version }}
          docker pull ${{ needs.init.outputs.phpcli-dev-docker-image-name }}:${{ needs.init.outputs.version-minor }}-py2-node${{ matrix.py2-node-version }}
          docker pull ${{ needs.init.outputs.phpcli-dev-docker-image-name }}:${{ needs.init.outputs.version-major }}-py2-node${{ matrix.py2-node-version }}
          docker pull ${{ needs.init.outputs.phpcli-dev-docker-image-name }}:latest

  cleanup:

    runs-on: ubuntu-20.04
    needs: [push]
    steps:
      - uses: joutvhu/delete-artifact@v1
        with:
          name: |
            phpcli-prd
            phpcli-dev
